export {
  slugify,
  normalizeText,
  normalizeBrandName,
  normalizeIngredientName,
  normalizeCanonicalName,
  normalizeUpc,
  normalizeCountryCode,
  normalizeUrl,
  normalizePackageSizeLabel,
  parsePackageSizeToGrams,
  normalizeList,
  normalizeNumeric,
  normalizeBoolean,
} from './normalizer';
